label-studio:
 url:                 # Local host URL
 api-token:           # Label Studio API Token
 db-and-media-dir:    # Database and Media Directory
 project-id:          # Project ID

path:
 audio: ./data
